import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  //Screen Welcome
  containerWelcome: {
    flex: 1,
    flexDirection: "column",
    backgroundColor:"#7bd6c6",
    alignItems: "center",
    justifyContent: "center",
  },
  textWelcome: {
    marginVertical: 15,
    marginHorizontal: 15,
    fontFamily: "montserrat-bold",
    fontSize: 24,
    textAlign: "center",
    color:"#fff"
  },
  buttonWelcome: {
    alignItems: "center",
    padding: 20,
    marginVertical: 25,
    backgroundColor: "#F27798",
    color: "#fff",
    fontSize: 18,
    borderRadius: 10,
    fontFamily: "montserrat-semi-bold",
  },
  containerModal: {
    flex: 1,
    alignItems:'center',
    backgroundColor: '#7bd6c6',
    paddingTop: 25,
  },
  titleModal: {
    fontFamily: 'montserrat-semi-bold',
    fontSize: 22,
    color: '#fff',
    textAlign: 'center',
  },
  textInfoModal: {
    fontFamily: 'montserrat',
    color: '#fff',
    fontSize: 16,
    alignSelf: 'center',
    justifyContent:'center',
    margin: 20,
  },
  buttonClose: {
    textAlign: 'center',
    padding: 12,
    width: 150,
    alignSelf: 'center',
    marginHorizontal: 10,
    marginVertical: 20,
    backgroundColor: '#F27798',
    fontFamily: 'montserrat-semi-bold',
    color: '#fff',
    fontSize: 18,
    borderRadius: 10,
  },
  // Screen Home
  containerHome: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#7bd6c6",
    alignItems: "stretch",
    paddingTop: 50,
  },
  item: {
    backgroundColor: "#3cc3ac",
    padding: 14,
    borderRadius: 10,
    marginVertical: 8,
    marginHorizontal: 21,
  },
  itemText: {
    fontSize: 13,
    color: "#fff",
    fontFamily: "montserrat-semi-bold",
  },
  title: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  every: {
    borderWidth: 1,
    borderColor: "#5bccb9",
    borderRadius: 5,
    padding: 15,
    margin: 10,
    backgroundColor: "#5bccb9",
  },
  meal: {
    color: "#fff",
    fontFamily: "montserrat-semi-bold",
    fontSize: 16,
  },

  //Screen Meal (Add meal Form)
  containerMeal: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#7bd6c6",
    alignItems: "stretch",
    paddingTop: 25,
    color: "#000",
  },
  titleMeal: {
    fontFamily: "montserrat-bold",
    fontSize: 22,
    color: "#fff",
    textAlign: "center",
    marginTop: 15,
  },
  form: {
    flex: 1,
    padding: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#5bccb9",
    borderRadius: 5,
    padding: 10,
    margin: 10,
    fontFamily: "montserrat",
    fontSize: 16,
    backgroundColor: "#5bccb9",
    color:"#fff",
  },
  messageError: {
    paddingBottom: 5,
    paddingHorizontal: 15,
    fontFamily: "montserrat",
    fontSize: 10,
    color: "red",
  },
  buttonSave: {
    textAlign: "center",
    padding: 15,
    marginHorizontal: 10,
    marginVertical: 20,
    backgroundColor: "#F27798",
    color: "#fff",
    fontSize: 18,
    borderRadius: 10,
    fontFamily: "montserrat-semi-bold",
  },
  // Screen List of meals
  closeIcon: {
    alignSelf: "flex-end",
    marginRight: 25,
  },
  itemList: {
    backgroundColor: "#3cc3ac",
    padding: 20,
    borderRadius: 10,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  itemTextList: {
    fontSize: 18,
    color: "#fff",
    fontFamily: "montserrat-semi-bold",
  },
  itemSubList: {
    fontSize: 13,
    color: "#ededed",
    fontFamily: "montserrat-semi-bold",
  },
  buttonAdd: {
    textAlign: "center",
    padding: 10,
    width: 100,
    alignSelf: "flex-end",
    marginHorizontal: 10,
    marginVertical: 20,
    backgroundColor: "#F27798",
    color: "#fff",
    fontSize: 14,
    borderRadius: 10,
    fontFamily: "montserrat-semi-bold",
  },
});
